name: "Run linters on push"
on: [push]
jobs:
    type-checking:
        name: "Run type checking"
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun ts-check

    lint:
        name: "Run linters"
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun lint
